// <auto-generated />
using System;
using HospitalEnCasa.app.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HospitalEnCasa.app.Persistencia.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HospitalEnCasa.app.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cedula")
                        .HasColumnType("int");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int>("genero")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("cedula")
                        .IsUnique();

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("HospitalEnCasa.app.Dominio.Enfermera", b =>
                {
                    b.HasBaseType("HospitalEnCasa.app.Dominio.Persona");

                    b.Property<string>("hospital")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Enfermera_hospital");

                    b.Property<string>("informacion_laboral")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Enfermera");
                });

            modelBuilder.Entity("HospitalEnCasa.app.Dominio.Medico", b =>
                {
                    b.HasBaseType("HospitalEnCasa.app.Dominio.Persona");

                    b.Property<string>("hospital")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tarjeta_profesional")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Medico");
                });

            modelBuilder.Entity("HospitalEnCasa.app.Dominio.Paciente", b =>
                {
                    b.HasBaseType("HospitalEnCasa.app.Dominio.Persona");

                    b.Property<string>("direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("enfermeraId")
                        .HasColumnType("int");

                    b.Property<int>("latitud")
                        .HasColumnType("int");

                    b.Property<int>("longitud")
                        .HasColumnType("int");

                    b.Property<int?>("medicoId")
                        .HasColumnType("int");

                    b.HasIndex("enfermeraId");

                    b.HasIndex("medicoId");

                    b.HasDiscriminator().HasValue("Paciente");
                });

            modelBuilder.Entity("HospitalEnCasa.app.Dominio.Paciente", b =>
                {
                    b.HasOne("HospitalEnCasa.app.Dominio.Enfermera", "enfermera")
                        .WithMany()
                        .HasForeignKey("enfermeraId");

                    b.HasOne("HospitalEnCasa.app.Dominio.Medico", "medico")
                        .WithMany()
                        .HasForeignKey("medicoId");

                    b.Navigation("enfermera");

                    b.Navigation("medico");
                });
#pragma warning restore 612, 618
        }
    }
}
